name: Build Sycomore (Windows)
on: push

jobs:
  build:
    runs-on: windows-latest
    name: Windows Server 2019
    steps:
      - name: Configure environment
        run: |
          echo "WORKSPACE=$Env:GITHUB_WORKSPACE" >> $Env:GITHUB_ENV
          echo "PYTHON=python" >> $Env:GITHUB_ENV
      - name: Checkout latest revision
        uses: actions/checkout@v2
      - name: Setup conda
        run: C:\Miniconda\condabin\conda.bat init powershell
      - name: Set up dev environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Configure the build
        run: .ci\windows\install.cmd
      - name: Build Sycomore
        run: .ci\windows\build.cmd
      - name: Run tests
        run: .ci\windows\post_build.cmd
