name: Build wheels (macOS)
on: [push, create]

jobs:
  build:
    runs-on: macos-10.15
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Python 3.5", python: cp35 }
          - { name: "Python 3.6", python: cp36 }
          - { name: "Python 3.7", python: cp37 }
          - { name: "Python 3.8", python: cp38 }
          - { name: "Python 3.9", python: cp39 }
    env:
      WORKSPACE: "${{ github.workspace }}"
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          # NOTE: setuptools_scm does not work well with the default shallow
          # clone.
          fetch-depth: 0
      - name: Get cibuildwheel
        run: python3 -m pip install cibuildwheel
      - name: Provision environment
        run: ./.ci/wheels/provision.sh
      - name: Build wheels
        run: python3 ./.ci/wheels/build.py '${{ matrix.python }}*'
      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist/*whl
